const dotenv = require("dotenv");
dotenv.config();

exports.config = {
  // SERVICE_PLATFORMS: comma-separated list of platforms (e.g., "shutterstock,getty,alamy")
  // Enables uploading to multiple platforms in a single pipeline run
  // Currently only "shutterstock" is implemented
  platforms: process.env.SERVICE_PLATFORMS || process.env.PLATFORMS || "shutterstock",
  localChromiumServer: process.env.LOCAL_CHROMIUM_SERVER,
  scanPicturesDirPath: process.env.SCAN_PICTURES_DIRECTORY,
  processedPicturesDirPath: process.env.PROCESSED_PICTURES_DIRECTORY,
  failedPicturesDirPath: process.env.FAILED_PICTURES_DIRECTORY,
  llm: {
    ollamaBaseUrl: process.env.OLLAMA_BASE_URL || "http://127.0.0.1:11434",
    model: process.env.OLLAMA_MODEL || "llama3",
    visionModel: process.env.OLLAMA_VISION_MODEL || "llama3.2-vision",
    requireVision: process.env.OLLAMA_REQUIRE_VISION !== "false",
    metadataContextPath: process.env.SHUTTERSTOCK_METADATA_CONTEXT_PATH || "./code-base/shutterstock-best-practices.md",
    temperature: Number(process.env.OLLAMA_TEMPERATURE || 0.2),
    maxRetries: Number(process.env.OLLAMA_MAX_RETRIES || 2),
    timeoutMs: Number(process.env.OLLAMA_TIMEOUT_MS || 60000),
    maxTagCount: Number(process.env.SHUTTERSTOCK_MAX_TAGS || 25),
    descriptionMinLength: Number(process.env.SHUTTERSTOCK_DESCRIPTION_MIN_LENGTH || 80),
    descriptionMaxLength: Number(process.env.SHUTTERSTOCK_DESCRIPTION_MAX_LENGTH || 200),
  },
  pipeline: {
    batchSize: Number(process.env.PIPELINE_BATCH_SIZE || 1),
    dryRun: process.env.PIPELINE_DRY_RUN !== "false",
    maxImagesPerRun: Number(process.env.PIPELINE_BATCH_SIZE || 1),
    maxMetadataRetries: Number(process.env.PIPELINE_MAX_METADATA_RETRIES || 4),
    uploadLogPath: process.env.PIPELINE_UPLOAD_LOG_PATH || "./data/upload-log.json",
    csvOutputPath: process.env.PIPELINE_CSV_OUTPUT_PATH || "./data/shutterstock-metadata-batch.csv",
  },
  metadataValidation: {
    titleMinLength: Number(process.env.SHUTTERSTOCK_TITLE_MIN_LENGTH || 8),
    titleMaxLength: Number(process.env.SHUTTERSTOCK_TITLE_MAX_LENGTH || 120),
    descriptionMinLength: Number(process.env.SHUTTERSTOCK_DESCRIPTION_MIN_LENGTH || 80),
    descriptionMaxLength: Number(process.env.SHUTTERSTOCK_DESCRIPTION_MAX_LENGTH || 200),
    minTagCount: Number(process.env.SHUTTERSTOCK_MIN_TAG_COUNT || 25),
    maxTagCount: Number(process.env.SHUTTERSTOCK_MAX_TAGS || 45),
  },
  shutterStock: {
    mode: process.env.SHUTTERSTOCK_MODE || "web_automation",
    contributorLink: process.env.SHUTTERSTOCK_CONTRIBUTOR_LINK || "https://submit.shutterstock.com/",
    username: process.env.SHUTTERSTOCK_USERNAME || "",
    password: process.env.SHUTTERSTOCK_PASSWORD || "",
    enableAntiBotDelays: process.env.SHUTTERSTOCK_ENABLE_ANTI_BOT_DELAYS !== "false", // false for testing
    keepBrowserOpenAfterUpload: process.env.SHUTTERSTOCK_KEEP_BROWSER_OPEN === "true",
    slowInteractionMinMs: Number(process.env.SHUTTERSTOCK_SLOW_MIN_MS || 1000),
    slowInteractionMaxMs: Number(process.env.SHUTTERSTOCK_SLOW_MAX_MS || 4800),
    loginButtonSelectors: [
      process.env.SHUTTERSTOCK_LOGIN_BUTTON_SELECTOR,
      'a[data-testid="button"]',
      'a[href*="login"]',
    ].filter(Boolean),
    loginUsernameSelectors: [
      process.env.SHUTTERSTOCK_LOGIN_USERNAME_SELECTOR,
      'input[type="email"]',
      'input[name="email"]',
      'input[autocomplete="username"]',
    ].filter(Boolean),
    loginPasswordSelectors: [
      process.env.SHUTTERSTOCK_LOGIN_PASSWORD_SELECTOR,
      `input[type='password'][data-test-id="password-input"]`,
      'input[autocomplete="current-password"]',
    ].filter(Boolean),
    uploadFileInputSelectors: [
      process.env.SHUTTERSTOCK_UPLOAD_FILE_INPUT_SELECTOR,
      `button[type='button'][data-testid="uploadButton"]`,
    ].filter(Boolean),
    loginPageUrlIncludes: [
      process.env.SHUTTERSTOCK_LOGIN_URL_INCLUDE,
      "contributor-accounts.shutterstock.com/login",
      "/auth",
      "/signin",
    ].filter(Boolean),
    uploadPageUrlIncludes: [
      process.env.SHUTTERSTOCK_UPLOAD_URL_INCLUDE,
      "submit.shutterstock.com/portfolio/not_submitted/photo",
      "submit.shutterstock.com/upload",
    ].filter(Boolean),
    contributorPageUrlIncludes: [process.env.SHUTTERSTOCK_CONTRIBUTOR_LINK, "submit.shutterstock.com"].filter(Boolean),
    loggedInSelectors: [
      process.env.SHUTTERSTOCK_LOGGED_IN_SELECTOR,
      '[data-testid="account-menu-button"]',
      '[data-testid="profile-button"]',
      'a[href*="logout"]',
      'button[aria-label*="account" i]',
    ].filter(Boolean),
    loginFormSelectors: [
      process.env.SHUTTERSTOCK_LOGIN_FORM_SELECTOR,
      'form[action*="login"]',
      'input[type="email"]',
      'input[type="password"]',
    ].filter(Boolean),
    uploadReadySelectors: [
      process.env.SHUTTERSTOCK_UPLOAD_READY_SELECTOR,
      `button[type='button'][data-testid="uploadButton"]`,
      'input[type="file"]',
    ].filter(Boolean),
    uploadTitleSelectors: [
      process.env.SHUTTERSTOCK_UPLOAD_TITLE_SELECTOR,
      'input[name="title"]',
      'input[placeholder*="title" i]',
    ].filter(Boolean),
    uploadDescriptionSelectors: [
      process.env.SHUTTERSTOCK_UPLOAD_DESCRIPTION_SELECTOR,
      'textarea[name="description"]',
      'textarea[placeholder*="description" i]',
      'textarea[placeholder*="caption" i]',
    ].filter(Boolean),
    uploadKeywordSelectors: [
      process.env.SHUTTERSTOCK_UPLOAD_KEYWORDS_SELECTOR,
      'textarea[name="keywords"]',
      'input[name="keywords"]',
      'input[placeholder*="keyword" i]',
      'textarea[placeholder*="keyword" i]',
    ].filter(Boolean),
    csvUploadModalButtonSelectors: [
        process.env.SHUTTERSTOCK_CSV_UPLOAD_MODAL_BUTTON_SELECTOR,
        `button[type='button'][data-testid="csv-upload"]`
    ],
    csvUploadFileInputSelectors: [
      process.env.SHUTTERSTOCK_CSV_UPLOAD_INPUT_SELECTOR,
      'input[type="file"][accept*=".csv"]',
      'input[type="file"][accept*=".csv" i]',
      'input[type="file"]',
    ].filter(Boolean),
    csvUploadSubmitSelectors: [
      process.env.SHUTTERSTOCK_CSV_UPLOAD_SUBMIT_SELECTOR,
      'button:has-text("Upload CSV")',
      'button:has-text("Import")',
      'button:has-text("Submit")',
      '[role="button"]:has-text("Upload CSV")',
    ].filter(Boolean),
    csvUploadSuccessSelectors: [
      process.env.SHUTTERSTOCK_CSV_UPLOAD_SUCCESS_SELECTOR,
      'text=CSV uploaded',
      'text=Import complete',
      'text=Metadata uploaded',
      'text=Upload complete',
    ].filter(Boolean),
    // uploadSaveDraftSelectors: [
    //   process.env.SHUTTERSTOCK_UPLOAD_SAVE_DRAFT_SELECTOR,
    //   'button:has-text("Save")',
    //   'button:has-text("Save draft")',
    //   '[role="button"]:has-text("Save")',
    // ].filter(Boolean),
    uploadSaveConfirmationSelectors: [
      process.env.SHUTTERSTOCK_UPLOAD_SAVE_CONFIRMATION_SELECTOR,
      "text=Saved",
      "text=Draft saved",
      "text=Changes saved",
    ].filter(Boolean),
    uploadModalButtonSelectors: [
        process.env.SHUTTERSTOCK_UPLOAD_MODAL_BUTTON_SELECTOR,
        `button[type='button'][data-testid="desktop-upload-button"]`
    ].filter(Boolean),
    uploadPageUrl: process.env.SHUTTERSTOCK_UPLOAD_PAGE_URL || "https://submit.shutterstock.com/upload",
    uploadSuccessTimeoutMs: Number(process.env.SHUTTERSTOCK_UPLOAD_SUCCESS_TIMEOUT_MS || 120000),
    stateCheckTimeoutMs: Number(process.env.SHUTTERSTOCK_STATE_CHECK_TIMEOUT_MS || 30000),
    trendsUrl: process.env.SHUTTERSTOCK_TRENDS_URL,
    trendsTagSelectors: [
      process.env.SHUTTERSTOCK_TRENDS_TAG_SELECTOR,
      `tbody[data-testid="trends-table-body"] td a`,
      "table tbody td",
      "table td",
    ].filter(Boolean),
    trendsLoadMoreButtonSelectors: [
      process.env.SHUTTERSTOCK_TRENDS_LOAD_MORE_SELECTOR,
      'button:has-text("Load more")',
      '[role="button"]:has-text("Load more")',
    ].filter(Boolean),
    trendsPageLoadTimeoutMs: Number(process.env.SHUTTERSTOCK_TRENDS_PAGE_LOAD_TIMEOUT_MS || 30000),
    categories: [
      "Abstract",
      "Animals/Wildlife",
      "Arts",
      "Backgrounds/Textures",
      "Beauty/Fashion",
      "Buildings/Landmarks",
      "Business/Finance",
      "Celebrities",
      "Education",
      "Food and drink",
      "Healthcare/Medical",
      "Holidays",
      "Industrial",
      "Interiors",
      "Miscellaneous",
      "Nature",
      "Objects",
      "Parks/Outdoor",
      "People",
      "Religion",
      "Science",
      "Signs/Symbols",
      "Sports/Recreation",
      "Technology",
      "Transportation",
      "Vintage",
    ],
  },
};
